name: on_push

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      - 
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7
      - 
        run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - 
        run: echo $SHA
        env:
          SHA: ${{ env.SHA }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kirskirill/diplomapp
          tags: ${{ env.SHA }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
